version: "3.8"
services:
  todo-app:
    build:
      context: .
    ports:
      - "${PORT:-5842}:${PORT:-5842}"
    environment:
      - DENO_ENV=development
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGODB_PROT:-27017}:${MONGODB_PROT:-27017}"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-}
    restart: unless-stopped

volumes:
  mongodb_data_container:
